version: 2
jobs:
    build:
        docker:
            - image: openjdk:8-jdk
        environment:
            _JAVA_OPTIONS: "-Xmx768m -Xms256m"
            GRADLE_OPTS: -Dorg.gradle.jvmargs=-Xmx1024m -Dorg.gradle.daemon=false
        steps:
            - run:
                name: Prepare System
                command: |
                    apt-get update && apt-get -y upgrade
                    apt-get install -y python3.7

            - checkout
            
            - run:
                name: Get Dependencies
                command: ./gradlew downloadDependencies --console plain
            - save_cache:
                key: artifact-download-cache-{{ .Revision }}
                paths:
                    - ~/.gradle
            - run:
                name: Run Build
                command: ./gradlew build --console plain --max-workers=2 -Dorg.gradle.daemon=false

            - run:
                name: Save test results
                command: |
                    mkdir -p ~/junit/
                    find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
                when: always
            - store_test_results:
                path: ~/junit
            - store_artifacts:
                path: ~/junit

  
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build

